name: Build and Deploy to GCE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  IMAGE: kaww
  REGISTRY: kaww
  INSTANCE: kaww  # TODO: update to instance name
  ZONE: us-central1   # TODO: update to instance zone

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |-
        cat ${{ secrets.KAG_AUTOCONFIG }} > autoconfig.cfg
        DOCKER_BUILDKIT=1 docker build \
          --quiet \
          --pull \
          --tag "$ZONE-docker.pkg.dev/$PROJECT_ID/$REGISTRY/$IMAGE:$GITHUB_SHA" \
          -f Dockerfile \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$ZONE-docker.pkg.dev/$PROJECT_ID/$REGISTRY/$IMAGE:$GITHUB_SHA"

    # Deploy the Docker image to the GCE
    - name: Deploy
      run: |-
        gcloud compute instances update-container "$INSTANCE" \
          --zone "$ZONE" \
          --container-image "$ZONE-docker.pkg.dev/$PROJECT_ID/$REGISTRY/$IMAGE:$GITHUB_SHA"